config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/dashboard', to: 'profiles#dashboard', as: :dashboard

  get 'profiles/show'

  get '/home', to: 'pages#home', as: :homepage
  get '/about', to: 'pages#about', as: :aboutpage
  get '/credits', to: 'pages#credits', as: :creditspage

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end 

  resources :statuses

  get 'feed', to: 'statuses#index', as: :feed
  root to: 'pages#home' #Nothing in the path - index

  get '/:id', to: 'profiles#show'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show

  	@user = User.find_by_profile_name(params[:id])
  	if @user
  		#@statuses = @user.statuses.paginate(page: params[:page], per_page: 50)
      @statuses = @user.statuses.where('private=? OR user_id=?', false, current_user).paginate(page: params[:page], per_page: 50).order('created_at DESC')
  		#@statuses = @user.statuses.all
  		render action: :show
  	else
  		render file: 'public/404', status: 404, formats: [:html]
  	end
  end


  def dashboard
    @user = User.find(current_user)
    if @user
      @dashstatuses = @user.statuses.where('private=? OR user_id=?', false, current_user).paginate(page: params[:page], per_page: 50).order('created_at DESC')
    else
      render file: 'public/pleaseregister'
    end
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/dashboard.html.erb
<div class="container">
	<h2>Dashboard</h2>

	<%= link_to 'New victory', new_status_path, class: "primary-button" %>

	<!-- Loop through victories -->
	<div class="col3-group group">
	<% @dashstatuses.each do |status| %>

	<div class="victory-item">
		<p><b><a href="/<%= status.user.profile_name %>"><%= status.user.full_name %></a></b><br />
		<%= status.content %></p>
		<p><%= time_ago_in_words(status.created_at) + ' ago' %></p>

		<%# if current_user == status.user %>
		<% if can? :update, status %>
	    	<%= link_to 'Edit', edit_status_path(status) %>
	    <% end %>

	    <% if can? :delete, status %>
	    	<%= link_to 'Delete', status, method: :delete, data: { confirm: 'Are you sure?' } %>
	    <% end %>

		<p><%= link_to 'Show', status %></p>
	</div>

	<% end %>
	</div>

	<%= will_paginate @dashstatuses %>

	<%= link_to 'New victory', new_status_path, class: "primary-button" %>


</div>

app/views/profiles/show.html.erb
<div class="profile-header">
	<svg width="100" height="100">
	<image xlink:href="<%= image_path("logo/king-crown.svg") %>" src="<%= image_path("logo/king-crown.png") %>" width="100" height="100" alt="Small Victories logo" />
	</svg>
	<h2><%= @user.full_name%></h2>

	<%= link_to 'New victory', new_status_path, class: "button" %>
</div>

<div class="whitewrap">
<div class="container">

	<% if @statuses %>
		<h3 class="profilemain c"><%= @statuses.count %> victories</h3>

		<div id="timeline">
		<% @statuses.each do |status| %>

			<div class="timeline-item">
				<div class="timeline-icon">
					<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
			width="21px" height="20px" viewBox="0 0 21 20" enable-background="new 0 0 21 20" xml:space="preserve">
						<path fill="#FFFFFF" d="M19.998,6.766l-5.759-0.544c-0.362-0.032-0.676-0.264-0.822-0.61l-2.064-4.999
			c-0.329-0.825-1.5-0.825-1.83,0L7.476,5.611c-0.132,0.346-0.462,0.578-0.824,0.61L0.894,6.766C0.035,6.848-0.312,7.921,0.333,8.499
			l4.338,3.811c0.279,0.246,0.395,0.609,0.314,0.975l-1.304,5.345c-0.199,0.842,0.708,1.534,1.468,1.089l4.801-2.822
			c0.313-0.181,0.695-0.181,1.006,0l4.803,2.822c0.759,0.445,1.666-0.23,1.468-1.089l-1.288-5.345
			c-0.081-0.365,0.035-0.729,0.313-0.975l4.34-3.811C21.219,7.921,20.855,6.848,19.998,6.766z"/>
					</svg>
				</div>
				<div class="<%= cycle('timeline-content', 'timeline-content right') -%>">
					<p><%= status.content %></p>
					<p><%= status.category.nil? ?  "No category" : status.category.cat_name %></p>
					<p><b><%= time_ago_in_words(status.created_at) %> ago</b></p>

					<%= link_to 'View', status_path(status), class: "button" %>
					
					<% if can? :update, status %>
				    	<%= link_to 'Edit', edit_status_path(status), class: "button" %>
				    <% end %>

				    <% if can? :delete, status %>
				    	<%= link_to 'Delete', status, method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %>
				    <% end %>
				</div>
			</div>

		<% end %>
		</div>

		<%= will_paginate @statuses %>
	<% end %>

</div>
</div>