config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/dashboard', to: 'profiles#dashboard', as: :dashboard

  get 'profiles/show'

  get '/home', to: 'pages#home', as: :homepage
  get '/about', to: 'pages#about', as: :aboutpage
  get '/credits', to: 'pages#credits', as: :creditspage

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end 

  resources :statuses

  get 'feed', to: 'statuses#index', as: :feed
  root to: 'pages#home' #Nothing in the path - index

  get '/:id', to: 'profiles#show'

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:destroy, :edit]

  # GET /statuses
  # GET /statuses.json
  def index
    #@statuses = Status.all
    #@statuses = Status.where(:private => false).or(:user_id => current_user).paginate(page: params[:page], per_page: 50).order('created_at DESC')
    #@statuses = Status.where('private=? OR user_id=?', false, current_user).paginate(page: params[:page], per_page: 50).order('created_at DESC')
    @statuses = Status.paginate(page: params[:page], per_page: 50).order('created_at DESC')
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    if can? :read, @status
      render action: :show
    else
      render file: 'public/pleaseregister'
    end
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @user = current_user
    @status = @user.statuses.build(status_params)

    #@status = Status.new(status_params)
    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    if can? :update, @status
    respond_to do |format|

        if @status.update(status_params)

          format.html { redirect_to @status, notice: 'Status was successfully updated.' }
          format.json { render :show, status: :ok, location: @status }
        else
          format.html { render :edit }
          format.json { render json: @status.errors, status: :unprocessable_entity }
        end

    end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    if can? :delete, @status
      @status.destroy
      respond_to do |format|

          format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
          format.json { head :no_content }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :content, :user_id, :private, :category_id)
    end

    def correct_user
      @status = current_user.statuses.find_by(id: params[:id])
      redirect_to root_url if @status.nil?
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= simple_form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

  <%#=f.input :user_id, collection: User.all, label_method: :full_name, input_html: { class: 'input' } %>
  <%= f.input :content, input_html: { class: 'input' } %>
  <%= collection_select(:status, :category_id, Category.all, :id, :cat_name, prompt: true) %>


  <div class="actions">
    <%= f.submit 'Submit', :class => 'primary-button' %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<div class="container">
<h1>Editing a victory</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>
</div>

app/views/statuses/index.html.erb
<div class="profile-header">
	<svg width="100" height="100">
	<image xlink:href="<%= image_path("logo/king-crown.svg") %>" src="<%= image_path("logo/king-crown.png") %>" width="100" height="100" alt="Small Victories logo" />
	</svg>
	<h2>Everyone's victories</h2>
</div>

<div class="whitewrap">
<div class="container">

	<!-- Loop through victories -->
	<div id="timeline">
	<% @statuses.each do |status| %>
		<div class="timeline-item">
			<div class="timeline-icon">
				<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
		width="21px" height="20px" viewBox="0 0 21 20" enable-background="new 0 0 21 20" xml:space="preserve">
					<path fill="#FFFFFF" d="M19.998,6.766l-5.759-0.544c-0.362-0.032-0.676-0.264-0.822-0.61l-2.064-4.999
		c-0.329-0.825-1.5-0.825-1.83,0L7.476,5.611c-0.132,0.346-0.462,0.578-0.824,0.61L0.894,6.766C0.035,6.848-0.312,7.921,0.333,8.499
		l4.338,3.811c0.279,0.246,0.395,0.609,0.314,0.975l-1.304,5.345c-0.199,0.842,0.708,1.534,1.468,1.089l4.801-2.822
		c0.313-0.181,0.695-0.181,1.006,0l4.803,2.822c0.759,0.445,1.666-0.23,1.468-1.089l-1.288-5.345
		c-0.081-0.365,0.035-0.729,0.313-0.975l4.34-3.811C21.219,7.921,20.855,6.848,19.998,6.766z"/>
				</svg>
			</div>
			<div class="<%= cycle('timeline-content', 'timeline-content right') -%>">
				<p><b><a href="/<%= status.user.profile_name %>"><%= status.user.full_name %></a></b><br />
				<%= status.content %></p>
				<p><%= status.category.nil? ?  "No category" : status.category.cat_name %></p>
				<p><%= time_ago_in_words(status.created_at) + ' ago' %></p>

				<%= link_to 'View', status, class: "button" %>

				<%# if current_user == status.user %>
				<% if can? :update, status %>
			    	<%= link_to 'Edit', edit_status_path(status), class: "button" %>
			    <% end %>

			    <% if can? :delete, status %>
			    	<%= link_to 'Delete', status, method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %>
			    <% end %>

			</div>
		</div>
	<% end %>
	</div>

	<%= will_paginate @statuses %>

</div>
</div>

<div class="darkwrap">
<div class="container c">
<h2>Add your victories into the mix</h2>

<%= link_to 'New victory', new_status_path, class: "button" %>

</div>
</div>

app/views/statuses/new.html.erb
<div class="container">
<h1>Add a new victory</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>
</div>

app/views/statuses/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.user.full_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<p>Category: <%= @status.category.cat_name %></p>



<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>
</div>