config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/dashboard', to: 'profiles#dashboard', as: :dashboard

  get 'profiles/show'

  get '/home', to: 'pages#home', as: :homepage
  get '/about', to: 'pages#about', as: :aboutpage
  get '/credits', to: 'pages#credits', as: :creditspage

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end 

  resources :statuses

  get 'feed', to: 'statuses#index', as: :feed
  root to: 'pages#home' #Nothing in the path - index

  get '/:id', to: 'profiles#show'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-gb">
<head>
  <title>Small Victories</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300|Raleway:100,300|Didact+Gothic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <link rel="shortcut icon" href="favicon.ico"/>
</head>

<body>

<div class="header-wrapper<% if !current_page?(root_path) %> header-shortimg<% end %>">
  <div class="container">

    <header>
    <div id="logo" class="menuUp">
        <h1><a href="<%= root_path %>">Small Victories</a></h1>
        <div id="navToggle"><a href="#">
          <svg width="25" height="25">
            <image xlink:href="<%= image_path("menuicon/icon-menu.svg") %>" src="<%= image_path("menuicon/icon-png2x.png") %>" width="25" height="25" alt="Menu icon"></image>
          </svg></a>
        </div>
    </div>
    <nav>
        <ul>
            <% if user_signed_in? %>
                
                <li><%= link_to "My victories", root_url + current_user.profile_name %></li>
                <li><%= link_to "Others", feed_path %></li>
                <li><%= link_to "Log out", logout_path %></li>
                <li class="menu-svg">
                  <a href="<%= edit_user_registration_path %>">
                  <svg width="25" height="25">
                    <image xlink:href="<%= image_path("cog/settings.svg") %>" src="<%= image_path("cog/settings.png") %>" width="25" height="25" alt="Settings"></image>
                  </svg>
                  </a>
                </li>
              <% else %>
               
                <li><%= link_to "Log in", login_path %></li>
                <li><%= link_to "Register", register_path %></li>
                
              <% end %>
        </ul>
    </nav>
    </header>



    <!--
    <div class="logo-holder">
      <h1><a href="<%= root_path %>">Small Victories</a></h1>
    </div>

    <div class="nav-holder">
      <a href="#menu" class="menu-link">
          <svg width="25" height="25">
              <image xlink:href="<%= image_path("menuicon/icon-menu.svg") %>" src="<%= image_path("menuicon/icon-png2x.png") %>" width="25" height="25" alt="Menu icon"></image>
          </svg>
      </a>

      <nav id="menu" role="navigation">
          <ul>
              <% if user_signed_in? %>
                <li><%= link_to "Dashboard", dashboard_path %></li>
                <li><%= link_to "My victories", root_url + current_user.profile_name %></li>
                <li><%= link_to "Others", feed_path %></li>
                <li><%= link_to "Log out", logout_path %></li>
                <li>
                  <a href="<%= edit_user_registration_path %>">
                  <svg width="25" height="25">
                    <image xlink:href="<%= image_path("cog/settings.svg") %>" src="<%= image_path("cog/settings.png") %>" width="25" height="25" alt="Settings"></image>
                  </svg>
                  </a>
                </li>
              <% else %>
               
                <li><%= link_to "Log in", login_path %></li>
                <li><%= link_to "Register", register_path %></li>
                
              <% end %>
          </ul>
      </nav>
    </div>
    -->
  </div>

  <% if current_page?(root_path) %>
    <div id="banner" class="container">
      <div class="title">
        <svg width="100" height="100">
          <image xlink:href="<%= image_path("logo/king-crown.svg") %>" src="<%= image_path("logo/king-crown.png") %>" width="100" height="100" alt="Small Victories logo"></image>
        </svg>
        <h2>Sometimes it's the little things that matter</h2>
        <span class="byline">Keep track of and celebrate the small victories in your personal life &amp; career</span>
      </div>
      <ul class="actions">
        <%= link_to 'Log your victories', register_path, html_options = { class: 'button' } %>
      </ul>
    </div>
  <% end %>

</div>






<!-- Header -->
<!--
<header>
    <div class="container">
        <div class="logo-holder">
            <a href="<%= root_path %>">Small Victories</a>
        </div>
        
        <div class="nav-holder">
            <a href="#menu" class="menu-link">
                <svg width="25" height="25">
                    <image xlink:href="<%= image_path("menuicon/icon-menu.svg") %>" src="<%= image_path("menuicon/icon-png2x.png") %>" width="25" height="25" alt="Menu icon" />
                </svg>
            </a>

            <nav id="menu" role="navigation">
                <ul>
                    <li></li>
                    
                    <% if user_signed_in? %>
                      <li><%= link_to "Dashboard", dashboard_path %></li>
                      <li><%= link_to "My victories", root_url + current_user.profile_name %></li>
                      <li><%= link_to "Others", feed_path %></li>
                      <li><%= link_to "Log out", logout_path %></li>
                      <li>
                        <a href="<%= edit_user_registration_path %>">
                        <svg width="25" height="25">
                          <image xlink:href="<%= image_path("cog/settings.svg") %>" src="<%= image_path("cog/settings.png") %>" width="25" height="25" alt="Settings" />
                        </svg>
                        </a>
                      </li>
                    <% else %>
                      <li><%= link_to "Log in", login_path %></li>
                      <li><%= link_to "Register", register_path %></li>
                    <% end %>
                </ul>
            </nav>
        </div>
    </div>
</header>
-->

<% flash.each do |type, message| %>
  <!-- Notifications -->
  <p class="module <%= flash_class type %> flash-notification"><%= message %></p>
<% end %>


<%= yield %>

<!-- Footer -->
<footer role="contentinfo" style="background-color:#ED757A;">
    <div id="copyright" class="container">
      <p><small>&copy; 2016 <a href="http://recordssoundthesame.com">Records Sound the Same</a> | <%= link_to "Credits", creditspage_path %> | <%= link_to "About", aboutpage_path %></small></p>
    </div>
</footer>

</body>
</html>